// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_S1JzWReO1MH-HtLNOgyC3gwGP9V33NE',
    appId: '1:370106019117:web:f5075e70a1d5c979ccf7a4',
    messagingSenderId: '370106019117',
    projectId: 'obnutries',
    authDomain: 'obnutries.firebaseapp.com',
    storageBucket: 'obnutries.appspot.com',
    measurementId: 'G-41N6HSVK6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUf5rzXSjA0dNpsVf1azCzmCIrsQ8H-tI',
    appId: '1:370106019117:android:cc1b0bec86361766ccf7a4',
    messagingSenderId: '370106019117',
    projectId: 'obnutries',
    storageBucket: 'obnutries.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlMEFDEblJgvBWPD6TRR2kgIyv_B_pQ8',
    appId: '1:370106019117:ios:695db263b1adbe77ccf7a4',
    messagingSenderId: '370106019117',
    projectId: 'obnutries',
    storageBucket: 'obnutries.appspot.com',
    iosBundleId: 'com.example.diagrams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlMEFDEblJgvBWPD6TRR2kgIyv_B_pQ8',
    appId: '1:370106019117:ios:3d21b10b4a663ffaccf7a4',
    messagingSenderId: '370106019117',
    projectId: 'obnutries',
    storageBucket: 'obnutries.appspot.com',
    iosBundleId: 'com.example.diagrams.RunnerTests',
  );
}
